const news = [
  {
    id: '0',
    title: 'Суперкомпьютер из США Frontier вышиб «японца» Fugaku с первого места',
    description: 'Первая тройка стран-владельцев чемпионских суперкомпьютеров в свежайшем рейтинге выглядит так: США, Япония, Финляндия.',
    image: 'https://www.it-world.ru/upload/iblock/eaa/resize_700_467_7ottrwbvllkgkgbrohatercu6ry05dbc_s.webp',
    authorId: '0',
    datePosted: '31.05.2022',
    isApproved: true,
  },
  {
    id: '3',
    title: 'Гендиректор Ford: грядет эра недорогих электромобилей',
    description: 'Джим Фарли считает, что на рынке электромобилей начнется ценовая война, когда появятся новые модели стоимостью $25 000.',
    image: 'https://www.it-world.ru/upload/iblock/8f5/resize_700_467_37nid0xbppiu0hgyrjt6lvf6w9jn38sb_s.webp',
    authorId: '0',
    datePosted: '02.06.2022',
    isApproved: true,
  },
  {
    id: '5',
    title: 'Илон Маск: прототип робота Optimus будет готов к 30 сентября',
    description: 'Человекообразный робот от Tesla будет построен из тех же комплектующих, что и электромобиль компании.',
    image: 'https://www.it-world.ru/upload/iblock/618/resize_700_467_eot1ha8twxyds8ohr0z0b1llzwrh9j0g_s.webp',
    authorId: '1',
    datePosted: '04.06.2022',
    isApproved: true,
  },
  {
    id: '4',
    title: 'Поставки видеокарт в I кв. 2022 года выросли на 32%',
    description: 'Согласно отчету Jon Peddie Research, на рынке дискретных графических карт произошли значительные изменения...',
    image: 'https://www.it-world.ru/upload/iblock/aff/resize_700_467_joyv9haquf7m6xr0d1x2890t8p1sqo4d_s.webp',
    authorId: '1',
    datePosted: '07.06.2022',
    isApproved: false,
  },
  {
    id: '1',
    title: 'Sony выходит в космос',
    description: 'Sony Corporation of America создала дочернюю компанию Sony Space Communications Corporation, которая займется разработкой устройств, позволяющих спутн...',
    image: 'https://www.it-world.ru/upload/iblock/d87/resize_700_467_p7wi9a7ieisawhfs1vqoinofydwofa1f_s.webp',
    authorId: '0',
    datePosted: '07.06.2022',
    isApproved: true,
  },
  {
    id: '2',
    title: 'WWDC22',
    description: 'В понедельник Apple начала свою ежегодную всемирную конференцию разработчиков WWDC22.',
    image: 'https://www.it-world.ru/upload/iblock/ab8/resize_700_466_0cqqp7eh0kpmliry3ybj3bk6n8zbqkny_s.webp',
    authorId: '1',
    datePosted: '07.06.2022',
    isApproved: false,
  },
];

export default news;
